DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS user_company_memberships CASCADE;
DROP TYPE  IF EXISTS user_role;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS "uuid-ossp";
